
services:
    app:
        build:
            context: .
            dockerfile: Dockerfile
        container_name: php_app
        volumes:
            - .:/var/www/html
        ports:
            - '8080:80'
        networks:
            - app-network
        depends_on:
            - db
        environment:
            MYSQL_HOST: db
            MYSQL_USER: root
            MYSQL_PASSWORD: hidran
            MYSQL_DB: corsophp
        restart: always

    db:
        image: mysql:8.0
        container_name: mysql_db
        environment:
            MYSQL_ROOT_PASSWORD: hidran
            MYSQL_DATABASE: corsophp
            MYSQL_PASSWORD: hidran
        volumes:
            - db_data_mysql:/var/lib/mysql
            - ./data:/docker-entrypoint-initdb.d/ # Mount the data folder
        ports:
            - '3309:3306'
        networks:
            - app-network
        restart: always

    phpmyadmin:
        image: phpmyadmin/phpmyadmin
        #container_name: phpmyadmin
        environment:
            PMA_HOST: db
            MYSQL_ROOT_PASSWORD: hidran
        ports:
            - '8081:80'
        networks:
            - app-network
        restart: always

volumes:
    db_data_mysql:

networks:
    app-network:
        driver: bridge
